xitongguanli/xitongdemo/SafetyProductionSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from user import views 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls')),  # 用户管理
    url(r'^organization/' , include('organization.urls')),#组织管理
    url(r'^$' , views.login , name = 'login' ),

]

xitongguanli/xitongdemo/user/urls.py
from django.conf.urls import url
from . import views

app_name = "user"

urlpatterns = [
    # ------------------- 用户登陆url  ----------------------------
    url(r'^login/$', views.login, name='login'),  # 用户登陆
    url(r'^login_out/$', views.login_out, name="login_out"),  # 用户退出

    # ------------------- 系统首页的url  ----------------------------
    url(r"^choice/$", views.choice, name="choice"),  # 选择用户和组织
    url(r'^starter/$', views.starter, name='starter'),  # 系统首页
    #---------------------搜索-------------------------------
    url(r"^search/$" , views.search , name = "search"),

    # ------------------- 用户CRUD的url  ----------------------------
    url(r'^user/$', views.show_all_user, name="show_all_user"),  # 点击用户进入用户界面
    url(r'^(?P<u_id>\d+)/user_details/', views.user_details, name="user_details"),  # 展示用户详情页面
    url(r'^add_user/$', views.add_user, name='add_user'),  # 新增用户
    url(r'^(?P<u_id>\d+)/edit_user/$', views.edit_user, name='edit_user'),  # 修改用户
    url(r'^(?P<u_id>\d+)/delete/$', views.delete, name='delete'),  # 删除用户


    # ------------------- 角色CRUD的url  ----------------------------
    url(r'^role/$', views.show_all_role, name='show_all_role'),  # 显示所有操作项和角色
    url(r'^new_role/$', views.new_role, name='new_role'),  # 新建角色
    url(r'^edit_role/(?P<rid>\d+)/$', views.edit_role, name='edit_role'),  # 编辑角色
    url(r'^del_role/$', views.del_role, name='del_role'),  # 删除(停用)角色

    #---------------------角色权限--------------------------------------
    url(r'^show_opeartion/$' , views.show_opeartion , name = "show_opeartion"),
    url(r'^show_role/$' , views.show_role , name = "show_role"),
]

xitongguanli/xitongdemo/user/models.py
from django.db import models


# 新建一个行为表，用来定义点击菜单路由后出现的数据类型
# 如果为列表，则规定只显示新建和搜索按钮


class Menu(models.Model):
    """
    菜单表
    """
    title = models.CharField(max_length=10, verbose_name='菜单名称')
    order = models.IntegerField(blank=True, default=1, verbose_name='排序')
    is_active = models.SmallIntegerField(default=1, verbose_name='是否激活')
    created_at = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='最后更新时间', auto_now_add=True)
    parent = models.ForeignKey('self', null=True, blank=True, verbose_name='父级菜单')
    url = models.URLField( verbose_name='路由')

    # 定义菜单间的自引用关系
    # 权限url 在 菜单下；菜单可以有父级菜单；还要支持用户创建菜单，因此需要定义parent字段（parent_id）
    # blank=True 意味着在后台管理中填写可以为空，根菜单没有父级菜单

    def __str__(self):
        # 显示层级菜单
        title_list = [self.title]
        p = self.parent
        while p:
            title_list.insert(0, p.title)
            p = p.parent
        return '-'.join(title_list)
    # join()中的sequence元素必须都为字符串，将其按照一定的连接符连接起来


class Operation(models.Model):
    """
    操作表
    """
    title = models.CharField(max_length=10, verbose_name='操作名称')
    url = models.URLField(blank=True, null=True, verbose_name='排序')
    is_active = models.SmallIntegerField(default=1, verbose_name='是否激活')
    created_at = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    menu = models.ForeignKey(Menu, null=True, blank=True)
    key = models.CharField(max_length=10,verbose_name='关键词')

    def __str__(self):
        # 显示带菜单前缀的权限
        return '{menu}---{permission}'.format(menu=self.menu, permission=self.title)


class Role(models.Model):
    """
    角色表
    """
    name = models.CharField(max_length=30, verbose_name='角色名称')
    is_select = models.SmallIntegerField(default=1, verbose_name='是否被选用')
    created_at = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='最后更新时间', auto_now_add=True)
    operations = models.ManyToManyField(Operation, verbose_name='操作')

    # 定义角色和权限的多对多关系

    def __str__(self):
        return self.name


class User(models.Model):
    """
    用户表
    """
    username = models.CharField(max_length=32, verbose_name='用户名称')
    password = models.CharField(max_length=64, verbose_name='密码')
    is_active = models.SmallIntegerField(default=1, verbose_name='是否激活')
    created_at = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='最后更新时间', auto_now_add=True)
    organization = models.ForeignKey('organization.Organization', blank=True, null=True, verbose_name='绑定员工')
    roles = models.ManyToManyField(Role, verbose_name='绑定角色')

    # 定义用户和角色的多对多关系

    def __str__(self):
        return self.username

xitongguanli/xitongdemo/user/views.py
from django.shortcuts import render, redirect ,reverse
from .models import User, Role, Operation, Menu
from organization.models import Organization
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from django.http import JsonResponse
# from django.views.decorators.csrf import csrf_exempt
# from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import render_to_response 
from django.db import connection
from django.core import serializers
import json
from itertools import chain
import split
from helper import *
from django.views.decorators.cache import cache_page
# ------------------------首页------------------




# 首页
def starter(request):

    return render(request, 'user/starter.html', {'menu_list': menu_data(request.session['menu_id'])})


# ------------------------用户------------------

# 用户登陆
def login(request):
    if request.method == "GET":
        return render(request, "user/login.html")
    elif request.method == "POST":
        # 获取用户数据
        username = request.POST["username"]
        password = request.POST["password"]
        # 从数据库中查询数据是否存在
        user_obj = User.objects.filter(username=username, password=password).first()
        # print(user_obj)


        # 判断账户名密码是否正确
        if not user_obj:
            return render(request, "user/login.html", {"error": '用户名或密码错误'})
        else:
            
            # 登陆成功跳转到选择角色的页面
            request.session["login"] = user_obj

            return redirect('user:choice')



# 选择角色和组织

def choice(request):
    if request.method == "GET":
        # 从数据库中查询角色和组织机构信息， 展示到前端,供登录用户选择。
        # 获取用户
        user = request.session.get('login')
        role_list = user.roles.all()
        # request.session["allrole"] = role_list
        # organization_list = Organization.objects.filter(parent=user.organization)
        return render(request, "user/choice.html", {"role_list": role_list})
    elif request.method == "POST":
        # 获取登录客户选择的数据，从数据库中读取需要展示的数据
        role_id = request.POST['role_id'] # 根据用户选择的角色，可以决定用户拥有的操作权限
        role = Role.objects.get(id=role_id) # 获取选择的角色
        request.session["role_id"] = role_id
        request.session['role'] = role
        # organization_id = request.POST['organization_id']  # 根据用户选择的部门，可以展示该分公司下的数据信息
        # organization = Organization.objects.get(id=organization_id)
        # request.session["organization"] = organization
        # 角色和部门都已经确定，由此可以确定首页展示的数据
        userdata = []
        keydata = []
        cursor = connection.cursor()
    #从角色，用户及其中间表中取他们相对应的关系
        cursor.execute("SELECT * FROM user_role AS a , user_user AS b , user_user_roles AS c ,user_role_operations AS d , user_operation AS e WHERE a.id = c.role_id AND b.id = c.user_id AND a.id = d.role_id AND d.operation_id = e.id AND b.username = '%s' AND a.id ='%s' "%( request.session["login"],request.session["role_id"]))
        for row in cursor.fetchall():
            usertable = {
                'menu_id':row[22],
                'key':row[21],
                'url':row[24 ]
            }
            
            userdata.append(usertable)   
        cursor.close()
        request.session['menu'] = userdata
        menudata = []
        for i in userdata:
            menudata.append(i['menu_id'])
        print(menudata)
        request.session['menu_id'] = menudata
        return redirect('user:starter')

# 用户退出
def login_out(request):
    #     清除session缓存
    request.session.flush()
    #     跳转至登录页面
    return redirect('/user/login/')

#查看角色
def show_role(request):
    # print(request.body)
    user_id = request.GET.get('user_id')
    # print(user_id)
    roledata = []
    cursor = connection.cursor()
    #从角色，用户及其中间表中取他们相对应的关系
    cursor.execute("SELECT * FROM user_role AS a , user_user AS b , user_user_roles AS c  WHERE a.id = c.role_id AND b.id = c.user_id AND b.id = '%s' "%user_id)
    for row in cursor.fetchall():
        roletable = {
            'role_name':row[1]
        }
        roledata.append(roletable)   
    cursor.close()
    # print(roledata)
    return HttpResponse(json.dumps({"status":"ok" , "data":roledata}) , content_type="application/json");





# 用户
def show_all_user(request):
    # 查询所有用户
    if request.method == "GET":
        action = request.GET.get("action")
        menuid = request.GET.get("id")
        
    power =  checkpower(menuid , request.session['login'] , request.session['role_id'])
    request.session['powerdata'] = power
    # a = read(menuid)
    # print(a)
    # 实例化结果集, 每页15条， 少于2条合并到上一页
    # a = test(menuid , request.session['role_id'] , request.session['login'])
   

    alluser =[]
    cursor = connection.cursor()
  
    cursor.execute('SELECT * FROM  user_user ')
     
    for row in cursor.fetchall():
        usertable = {
            'id':row[0],
            'username':row[1],
            'created_at':str(row[4]),
            'is_active':row[3],
        }
        alluser.append(usertable)
    # print(sb)    
    cursor.close()
    paginator = Paginator(alluser, 10)
    # 网页中的page值
    page = request.GET.get("page")
    # print(sb)
    try:
        # 传递HTML当前页对象
        alluser = paginator.page(page)
    except PageNotAnInteger:
        alluser = paginator.page(1)
    except EmptyPage:
        alluser = paginator.page(paginator.num_pages)
    
    
    return render(request, "user/show_all_user.html", {'alluser':alluser, 'menu_list': menu_data(request.session['menu_id']) , 'action':action , 'id':menuid})


# 展示用户详情
def user_details(request, u_id):
    # 查询用户信息
    user = User.objects.filter(id=u_id).first()
    # 查询组织机构信息
    organization = Organization.objects.all()
    # 查询组织机构表中的父ID
    organization_id = Organization.objects.filter(id=user.organization_id).first()
    print(organization_id)
    if organization_id.parent_id == None:
        role_obj = User.objects.filter(id=u_id).first()
        role_list = role_obj.roles.all()
        return render(request, "user/user_details.html",
                      {"user": user, "role_list": role_list, 'menu_list': menu_data(request.session['menu_id']), \
                                                         'organization': organization})
    else:
        parent_id = organization_id.parent.id
        # print(organization_id.type)
        # print("父id：%s" % parent_id)
        if organization_id.type > 2:
            # 遍历所有的组织
            for x in organization:
                # 判断父id属于哪个组织
                if parent_id == x.id and x.parent_id != None:
                    organizations = x.name
                
                    for u in organization:
                        # 判断上层父ID属于哪个组织
                        if x.parent_id == u.id:
                            or_id = u.name

            # 查询用户对应角色的信息
            # 多对多表查询
            role_obj = User.objects.filter(id=u_id).first()
            role_list = role_obj.roles.all()
            return render(request, "user/user_details.html", {"user": user, "role_list": role_list, 'menu_list': menu_data(request.session['menu_id']), \
                                                              'or_id': or_id, 'organizations': organizations})
        else:
            role_obj = User.objects.filter(id=u_id).first()
            role_list = role_obj.roles.all()
            return render(request, "user/user_details.html", {"user": user, "role_list": role_list, 'menu_list': menu_data(request.session['menu_id'])})



# 新增用户
def add_user(request):
    if request.method == "GET":
        # 查找角色所有数据
        role_list = Role.objects.all()
        return render(request, "user/add_user.html", {"role_list": role_list, 'menu_list': menu_data(request.session['menu_id'])})
    elif request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        role = request.POST.getlist("role_id")
        # 创建并保存到数据库
        user = User.objects.filter(username=username)
        if user:
            error = '账户已存在'
            return render(request, "user/add_user.html", {'error': error})
        else:
            user = User.objects.create(username=username, password=password)
            user.save()
            user.roles.add(*role)
            return render(request, 'user/add_user.html', {'msg': '添加成功' , 'menu_list':menu_data(request.session['menu_id'])})


# 修改用户
def edit_user(request, u_id):
    if request.method == "GET":
        user = User.objects.get(id=u_id)
        # 查询所有用户
        user_list = User.objects.all()
        # 查找角色所有数据
        role_list = Role.objects.all()
        user_id = u_id
        cursor = connection.cursor()
        cursor.execute("SELECT is_active FROM user_user  WHERE id = '%s'"%user_id)
        is_active= cursor.fetchall()
         
        cursor.close()
        # print(is_active[0][0])
        return render(request, "user/edit_user.html", {'pression':is_active[0][0] ,"role_list": role_list, 'user': user, "user_list": user_list, "menu_list": menu_data(request.session['menu_id'])})
    elif request.method == "POST":
        # 通过ID找到到要修改的数据
        print(request.POST)
        user = User.objects.filter(id=u_id).first()
        # 修改数据
        user.username = request.POST["username"]
        user.password = request.POST["password"]
        user.is_active = request.POST["is_active"]
        # 获取修改的角色
        role = request.POST.getlist("role_id")
        # 清楚原来的信息
        user.roles.clear()
        # 更新数据
        user.save()
        # 增加关联的角色
        user.roles.add(*role)
        return redirect('user:show_all_user')



# 删除用户
def delete(request, u_id):
    # 从数据库中查询要删除的用户
    user = User.objects.filter(id=u_id).first()
    # 改变用户状态为不活动
    user.is_active = 0
    # 更新到数据库
    user.save()
    # alluser =[]
    # cursor = connection.cursor()
  
    # cursor.execute('SELECT * FROM user_role AS a , user_user AS b , user_user_roles AS c  WHERE a.id = c.role_id AND b.id = c.user_id')
     
    # for row in cursor.fetchall():
    #     usertable = {
    #         'id':row[5],

xitongguanli/xitongdemo/user/templates/user/choice.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>选择角色和机构</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/static/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/static/plugins/iCheck/square/blue.css">
    <style>
        select{
                font-family: "微软雅黑";
                background: rgba(0,0,0,0);
                width: 100%;
                height: 40px;
                font-size: 18px;
                color: <div id="f8f8f8"></div>;
                margin-top:10px;
                text-align: center;
                border: 1px #dedede solid;
                border-radius: 5px;
            }
            option{
                color: black;
                background: #A6E1EC;
                line-height: 10px;
            }
            select:focus{
                border: 2px #ddd solid;
                box-shadow: 0 0 15px 1px #DDDDDD;
            }
            <!--option:hover{-->
                <!--background: #EBCCD1;-->
            <!--}-->
        }

    </style>

</head>

<body class="hold-transition login-page">
<div class="login-box" style="width:30%">
    <div class="login-logo">
        <b>##</b>管理系统
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">选择角色和组织</p>
        <form action="/user/choice/" method="post">
            {% csrf_token %}
            <div class="modal-content form-group">
                <div class="modal-body">
                    <label>请选择角色：</label>
                    <select id="role_id" name="role_id" style="width:auto, 0px; margin:auto;">
                        {% for role in role_list %}
                        <option value="{{role.id}}">---{{role.name}}---</option>
                        {% endfor %}
                    </select>
                    <!--<br><br>
                    <label >请选择组织：</label>
                    <select id="organization_id" name="organization_id" style="width:auto, 0px;">
                        {% for organization in organization_list %}
                        <option value="{{organization.id}}">---{{organization.name}}---</option>
                        {% endfor %}
                    </select>-->
                </div>
                <div class="modal-footer">
                    <a type="button" href="{% url 'user:login' %}"class="btn btn-default" data-dismiss="modal" style="float:left">取消</a>
                    <button type="submit" class="btn btn-primary">确定</button>
                </div>
            </div>
            <!-- /.col -->
        </form>
        <!-- /.social-auth-links -->

        <br/>

    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->


</body>
<script src="/static/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="/static/plugins/iCheck/icheck.min.js"></script>

<script type="text/javascript">
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</html>

xitongguanli/xitongdemo/user/templates/user/edit_role.html
{% extends 'base.html' %}
{% block css %}
<style type="text/css">
	#demo{
		text-align: center;
	}
</style>
{% endblock %}
{% block title %}
    
{% endblock %}
{% block checkpower %}
<a type="button" onClick="javascript :history.back(-1)"class="btn btn-default" >返回</a>
<input type="button" value="保存" class="btn btn-default" onclick="document.getElementById('myfrom').submit();">

{% endblock %}
{% block content %}
 <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header" style="background-color: #ffffe3;">
              <h3 class="box-title">管理用户</h3>
              <!-- <a href="{% url 'user:add_user' %}">添加新用户</a> -->
              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                

               
                </div>
              </div>
            </div>

  
    <form action="/user/edit_role/{{role.id}}/"  class="form-inline" id = "myfrom"method="POST">
        {% csrf_token %}
         <div  style="text-align: center;">
             <input type="text" name="name"class = "form-control" placeholder="角色" value="{{ role.name }}"/>
         </div>
     <div style="text-align: center;">
     {% for sb in pression %}
       	{% if sb == 1  %}
                      是否启用
                          <label class="radio-inline">
                          	
                            <input type="radio"  name="is_select" checked="checked" value="1"/>是
                            </label>
                            <label class="radio-inline">
                            <input type="radio" name="is_select"  value="0"/>否
                          </label>
                          {% else %}
                         <label class="radio-inline">
                            <input type="radio"  name="is_select" value="1"/>是
                            </label>
                            <label class="radio-inline">
                            <input type="radio" name="is_select" checked="checked" value="0"/>否
                         </label>
                          {% endif %}
{% endfor %}
</div>

   <hr/>
                  <div class="box-header" style="background-color: #ffffe3;">
                    <h3 class="box-title">修改权限</h3>
                  </div>
                  
         <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header" style="background-color: #ffffe3;">
              <h3 class="box-title">用户</h3>
              <!-- <a href="{% url 'user:add_user' %}">添加新用户</a> -->
              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="搜索">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tr>
                  <th><input type="checkbox" id = "fetchall" /></th>
                 
                  <th>菜单</th>
                 
                  <th>操作</th>
                  
                  
                </tr>
                
                       {% for data in operation_list %}
      
		<tr>
               <td><input type="checkbox" name="operation_id" value="{{data.id}}" /></td>
                <td>{{data.menu}}</td>
                <td>{{data.title}}</td>
            
		</tr>
  
          {% endfor %}
                
                </table>
      		 </div>
   

            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
                  
                  
                  
                  
                  

    </form>
         


            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
{% endblock %}
{% block javascript %}
<script type="text/javascript">
	$("#fetchall").click(function(){
		console.log("1111")
		
		if(this.checked){
			console.log("aa")
			$("[name=operation_id]:checkbox").remove('checked',false)
			$("[name=operation_id]:checkbox").prop('checked',true)
		}else{
			$("[name=operation_id]:checkbox").remove('checked',true)
			$("[name=operation_id]:checkbox").prop('checked',false)
		}
	})

//function selectAllCheck(obj, selname) {
//  var el = document.getElementsByName(selname);//获取所有复选框
//  var len = el.length;//获取复选框数量
//  if (obj.checked === true) {//判断全选框是否选中
//      $(obj).attr('title', '反选');
//      for (var i = 0; i < len; i++) {
//          if (!el[i].disabled) {//如果复选框未选中，设置选中状态
//              el[i].checked = true;
//          }
//      }
//  } else {//全选框未选中 将所有选中的复选框改为未选中
//      $(obj).attr('title', '全选');
//      for (var j = 0; j < len; j++) {//循环所有复选框
//          if (!el[j].disabled) {//复选框已选中
//              el[j].checked = false;
//          }
//      }
//  }
//}

	
</script>

{% endblock %}

xitongguanli/xitongdemo/user/templates/user/new_role.html
{% extends 'base.html' %} {% block title %} {% endblock %} 



{% block checkpower %}
<a type="button" onClick="javascript :history.back(-1)"class="btn btn-default" >返回</a>
<input type="button" value="保存" class="btn btn-default" onclick="document.getElementById('myfrom').submit();">
{% endblock %}


{% block content %}
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header" style="background-color: #ffffe3;">
				<h3 class="box-title">新建角色</h3>
				<!-- <a href="{% url 'user:add_user' %}">添加新用户</a> -->
				<div class="box-tools">
					<div class="input-group input-group-sm" style="width: 150px;">

					</div>
				</div>
			</div>

			<form method="POST" id = "myfrom" action="/user/new_role/">
				{% csrf_token %}
				<div style="text-align: center;">
					<input type="text" name="username" placeholder="角色名称" />
				</div>
				<div style="text-align: center;">
					是否被选用：
					<label class="radio-inline">
          <input type="radio"  name="is_select" value="1"/>  是
          </label>
					<label class="radio-inline"> 
            <input type="radio" name="is_select" value="0"/>否
        </label>
				</div>
                  <hr/>
                  <div class="box-header" style="background-color: #ffffe3;">
                    <h3 class="box-title">赋予权限</h3>
                  </div>
                  
       <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header" style="background-color: #ffffe3;">
              <h3 class="box-title">用户</h3>
              <!-- <a href="{% url 'user:add_user' %}">添加新用户</a> -->
              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="搜索">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tr>
                  <th><input type="checkbox" id = "fetchall" /></th>
                 
                  <th>菜单</th>
                 
                  <th>操作</th>
                  
                  
                </tr>
                
                       {% for data in operation_data %}
      
		<tr>
               <td><input type="checkbox" name="operation_id" value="{{data.id}}" /></td>
                <td>{{data.menu}}</td>
                <td>{{data.title}}</td>
            
		</tr>
  
          {% endfor %}
                
                </table>
      		 </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
                  
                  
                  
                  
                  

                  
                  
                  
				<!--<div style = "margin:0 auto; width:200px;  ">
			
				{% for data in operation_data %}
		       
        <div style = "text-align: center;">
	<div class="form-control">
		
               <input type="checkbox" name="operation_id" value="{{data.id}}" />
                &nbsp{{data.title}} &nbsp  &nbsp{{data.menu}}
            
         </div>  
</div>
				{% endfor %}
				
				
				</div>-->
				
				<h1>{{error}}</h1>
			</form>
		</div>
		<!-- /.box-body -->
	</div>
	<!-- /.box -->
</div>
</div>
{% endblock %}
{% block javascript %}
<script type="text/javascript">
	$("#fetchall").click(function(){
		console.log("1111")
		
		if(this.checked){
			console.log("aa")
			$("[name=operation_id]:checkbox").remove('checked',false)
			$("[name=operation_id]:checkbox").prop('checked',true)
		}else{
			$("[name=operation_id]:checkbox").remove('checked',true)
			$("[name=operation_id]:checkbox").prop('checked',false)
		}
	})
	</script>
{% endblock %}

xitongguanli/xitongdemo/user/templates/user/starter.html
{% extends 'base.html' %}

{% block checkpower %}
  
{% endblock %}

{% block content %}
    <section class="content container-fluid">

    </section>
{% endblock %}